package com.business.entity;

// Generated 2015-9-28 14:16:01 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TAuthConfig generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_auth_config", uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class AuthConfigEntity implements java.io.Serializable {

    private Long id;
    private String name;
    private String url;
    private Integer status;
    private Long pid;
    private Date createtime;
    private String operator;
    private Date operatetime;

    public AuthConfigEntity() {
    }

    public AuthConfigEntity(String name, String url, Integer status, Long pid, Date createtime) {
	this.name = name;
	this.url = url;
	this.status = status;
	this.pid = pid;
	this.createtime = createtime;
    }

    public AuthConfigEntity(String name, String url, Integer status, Long pid, Date createtime, String operator, Date operatetime) {
	this.name = name;
	this.url = url;
	this.status = status;
	this.pid = pid;
	this.createtime = createtime;
	this.operator = operator;
	this.operatetime = operatetime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
	return this.id;
    }

    public void setId(Long id) {
	this.id = id;
    }

    @Column(name = "name", unique = true, nullable = false, length = 40)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @Column(name = "url", nullable = false, length = 60)
    public String getUrl() {
	return this.url;
    }

    public void setUrl(String url) {
	this.url = url;
    }

    @Column(name = "status", nullable = false)
    public Integer getStatus() {
	return this.status;
    }

    public void setStatus(Integer status) {
	this.status = status;
    }

    @Column(name = "pid", nullable = false)
    public Long getPid() {
	return this.pid;
    }

    public void setPid(Long pid) {
	this.pid = pid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "createtime", nullable = false, length = 19)
    public Date getCreatetime() {
	return this.createtime;
    }

    public void setCreatetime(Date createtime) {
	this.createtime = createtime;
    }

    @Column(name = "operator", length = 45)
    public String getOperator() {
	return this.operator;
    }

    public void setOperator(String operator) {
	this.operator = operator;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "operatetime", length = 19)
    public Date getOperatetime() {
	return this.operatetime;
    }

    public void setOperatetime(Date operatetime) {
	this.operatetime = operatetime;
    }

}
