package com.business.entity;

// Generated 2015-9-28 14:16:01 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TManagerAuth generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_manager_auth")
public class ManagerAuthEntity implements java.io.Serializable {

    private Long id;
    private Long managerid;
    private Long authid;
    private Integer status;
    private Date createtime;
    private String operator;
    private Date operatetime;

    public ManagerAuthEntity() {
    }

    public ManagerAuthEntity(Long managerid, Long authid, Integer status, Date createtime) {
	this.managerid = managerid;
	this.authid = authid;
	this.status = status;
	this.createtime = createtime;
    }

    public ManagerAuthEntity(Long managerid, Long authid, Integer status, Date createtime, String operator, Date operatetime) {
	this.managerid = managerid;
	this.authid = authid;
	this.status = status;
	this.createtime = createtime;
	this.operator = operator;
	this.operatetime = operatetime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
	return this.id;
    }

    public void setId(Long id) {
	this.id = id;
    }

    @Column(name = "managerid", nullable = false)
    public Long getManagerid() {
	return this.managerid;
    }

    public void setManagerid(Long managerid) {
	this.managerid = managerid;
    }

    @Column(name = "authid", nullable = false)
    public Long getAuthid() {
	return this.authid;
    }

    public void setAuthid(Long authid) {
	this.authid = authid;
    }

    @Column(name = "status", nullable = false)
    public Integer getStatus() {
	return this.status;
    }

    public void setStatus(Integer status) {
	this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "createtime", nullable = false, length = 19)
    public Date getCreatetime() {
	return this.createtime;
    }

    public void setCreatetime(Date createtime) {
	this.createtime = createtime;
    }

    @Column(name = "operator", length = 45)
    public String getOperator() {
	return this.operator;
    }

    public void setOperator(String operator) {
	this.operator = operator;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "operatetime", length = 19)
    public Date getOperatetime() {
	return this.operatetime;
    }

    public void setOperatetime(Date operatetime) {
	this.operatetime = operatetime;
    }

}
