package com.business.entity;

// Generated 2015-9-28 14:16:01 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TManager generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_manager", uniqueConstraints = @UniqueConstraint(columnNames = "account"))
public class ManagerEntity implements java.io.Serializable {

    private Long id;
    private String account;
    private String password;
    private Integer status;
    private Date createtime;
    private String operator;
    private Date operatetime;

    public ManagerEntity() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
	return this.id;
    }

    public void setId(Long id) {
	this.id = id;
    }

    @Column(name = "account", unique = true, nullable = false, length = 40)
    public String getAccount() {
	return this.account;
    }

    public void setAccount(String account) {
	this.account = account;
    }

    @Column(name = "password", nullable = false, length = 40)
    public String getPassword() {
	return this.password;
    }

    public void setPassword(String password) {
	this.password = password;
    }

    @Column(name = "status", nullable = false)
    public Integer getStatus() {
	return this.status;
    }

    public void setStatus(Integer status) {
	this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "createtime", nullable = false, length = 19)
    public Date getCreatetime() {
	return this.createtime;
    }

    public void setCreatetime(Date createtime) {
	this.createtime = createtime;
    }

    @Column(name = "operator", length = 45)
    public String getOperator() {
	return this.operator;
    }

    public void setOperator(String operator) {
	this.operator = operator;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "operatetime", length = 19)
    public Date getOperatetime() {
	return this.operatetime;
    }

    public void setOperatetime(Date operatetime) {
	this.operatetime = operatetime;
    }

}
