package com.business.entity;

// Generated 2015-9-28 14:16:01 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * TSystemConfig generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_system_config", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class SystemConfigEntity implements java.io.Serializable {

    private Long id;
    private String code;
    private String name;
    private String value;
    private String memo;
    private Integer status;
    private Date createtime;
    private String operator;
    private Date operatetime;

    public SystemConfigEntity() {
    }

    public SystemConfigEntity(String code, String name, String value, Integer status, Date createtime) {
	this.code = code;
	this.name = name;
	this.value = value;
	this.status = status;
	this.createtime = createtime;
    }

    public SystemConfigEntity(String code, String name, String value, String memo, Integer status, Date createtime, String operator, Date operatetime) {
	this.code = code;
	this.name = name;
	this.value = value;
	this.memo = memo;
	this.status = status;
	this.createtime = createtime;
	this.operator = operator;
	this.operatetime = operatetime;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
	return this.id;
    }

    public void setId(Long id) {
	this.id = id;
    }

    @Column(name = "code", unique = true, nullable = false, length = 45)
    public String getCode() {
	return this.code;
    }

    public void setCode(String code) {
	this.code = code;
    }

    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
	return this.name;
    }

    public void setName(String name) {
	this.name = name;
    }

    @Column(name = "value", nullable = false, length = 2000)
    public String getValue() {
	return this.value;
    }

    public void setValue(String value) {
	this.value = value;
    }

    @Column(name = "memo", length = 2000)
    public String getMemo() {
	return this.memo;
    }

    public void setMemo(String memo) {
	this.memo = memo;
    }

    @Column(name = "status", nullable = false)
    public Integer getStatus() {
	return this.status;
    }

    public void setStatus(Integer status) {
	this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "createtime", nullable = false, length = 19)
    public Date getCreatetime() {
	return this.createtime;
    }

    public void setCreatetime(Date createtime) {
	this.createtime = createtime;
    }

    @Column(name = "operator", length = 45)
    public String getOperator() {
	return this.operator;
    }

    public void setOperator(String operator) {
	this.operator = operator;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "operatetime", length = 19)
    public Date getOperatetime() {
	return this.operatetime;
    }

    public void setOperatetime(Date operatetime) {
	this.operatetime = operatetime;
    }

}
