package com.business.entity;

// Generated 2015-9-28 14:16:01 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TShop generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "t_user_record")
public class UserRecordEntity implements java.io.Serializable {

    private Long id;
    private String realname;
    private String phone;
    private String accountbank;
    private Date createtime;

    public UserRecordEntity() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
	return this.id;
    }

    public void setId(Long id) {
	this.id = id;
    }

    @Column(name = "realname", nullable = false, length = 45)
    public String getRealname() {
	return realname;
    }

    public void setRealname(String realname) {
	this.realname = realname;
    }

    @Column(name = "phone", nullable = false, length = 20)
    public String getPhone() {
	return phone;
    }

    public void setPhone(String phone) {
	this.phone = phone;
    }

    @Column(name = "accountbank", nullable = false, length = 200)
    public String getAccountbank() {
	return accountbank;
    }

    public void setAccountbank(String accountbank) {
	this.accountbank = accountbank;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "createtime", nullable = false, length = 19)
    public Date getCreatetime() {
	return this.createtime;
    }

    public void setCreatetime(Date createtime) {
	this.createtime = createtime;
    }

}
