package com.business.dto.model;

import javax.xml.bind.annotation.XmlRootElement;

// Generated 2015-9-28 14:16:01 by Hibernate Tools 3.4.0.CR1


/**
 * TShop generated by hbm2java
 */
@XmlRootElement
public class AccountDTO implements java.io.Serializable {

	private Long id;
	private String account;
	private Integer status;
	private String statusString;
	private String createtime;
	private String operator;
	private String operatetime;
	private RestfulResult restfulResult;

	public AccountDTO() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getAccount() {
		return account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getCreatetime() {
		return createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	public String getOperator() {
		return operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	public String getOperatetime() {
		return operatetime;
	}

	public void setOperatetime(String operatetime) {
		this.operatetime = operatetime;
	}

	public RestfulResult getRestfulResult() {
		return restfulResult;
	}

	public void setRestfulResult(RestfulResult restfulResult) {
		this.restfulResult = restfulResult;
	}

	public String getStatusString() {
		return statusString;
	}

	public void setStatusString(String statusString) {
		this.statusString = statusString;
	}

	
}
